image:
    - Visual Studio 2015
    - Visual Studio 2017
    - Visual Studio 2019
    - Visual Studio 2022

init:
    - git config --global core.autocrlf input

clone_folder: c:\projects\cc_mqttsn
shallow_clone: true             

platform:
    - x64
    - x86

configuration:
    - Debug
    - Release

environment:
    COMMS_BRANCH: v5.2
    CC_MQTTSN_BRANCH: v2.3
    CC_MQTT311_BRANCH: v2.3

    matrix:
        - CPP_STD: 11
        - CPP_STD: 14
        - CPP_STD: 17
        - CPP_STD: 20

matrix:
    fast_finish: false
    exclude:
        - image: Visual Studio 2015
          CPP_STD: 17 
        - image: Visual Studio 2015
          CPP_STD: 20    
        - image: Visual Studio 2017
          CPP_STD: 20         

install:
    - call script\appveyor_install.bat
    - set PATH=%PATH%;%QTDIR%\bin
    - set BUILD_DIR=%APPVEYOR_BUILD_FOLDER%\build.%PLATFORM%.%CONFIGURATION%.%TOOLCHAIN%
    - if exist %BUILD_DIR% rmdir /S /Q %BUILD_DIR%
    - set COMMS_TAG=%COMMS_BRANCH%
    - set CC_MQTTSN_TAG=%CC_MQTTSN_BRANCH%
    - set CC_MQTT311_TAG=%CC_MQTT311_BRANCH%
    - set COMMON_INSTALL_DIR=%BUILD_DIR%\install
    - set COMMON_BUILD_TYPE=%CONFIGURATION%
    - set COMMON_CXX_STANDARD=%CPP_STD%
    - call script\prepare_externals.bat    

build_script:
    - echo ------------------------- Building Project -------------------------
    - cd %BUILD_DIR%
    - cmake .. -DCMAKE_BUILD_TYPE=%CONFIGURATION% -G "NMake Makefiles" -DCMAKE_INSTALL_PREFIX=install ^
        -DCMAKE_CXX_STANDARD=%CPP_STD% -DCMAKE_PREFIX_PATH="%COMMON_INSTALL_DIR%" ^
        -DCC_MQTTSN_BUILD_UNIT_TESTS=ON
    - cmake --build . --config %CONFIGURATION% --target install

test_script:
    - echo ------------------------- Testing -------------------------
    - ctest 

